# Generated by Django 5.2.12 on 2026-03-11 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "build_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("nvr", models.CharField(db_index=True, max_length=256, unique=True)),
                ("pkg_name", models.CharField(max_length=256)),
                ("version", models.CharField(max_length=128)),
                ("release", models.CharField(max_length=128)),
                ("build_type", models.CharField(default="rpm", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "builds",
                "ordering": ["-build_id"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=64, unique=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=128, unique=True)),
                ("ps_module", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
        migrations.CreateModel(
            name="Erratum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erratum_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "builds",
                    models.ManyToManyField(
                        blank=True, related_name="errata", to="sbom.build"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "errata",
            },
        ),
        migrations.CreateModel(
            name="StreamBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latest", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sbom.build"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sbom.stream"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stream builds",
                "unique_together": {("stream", "build")},
            },
        ),
        migrations.AddField(
            model_name="build",
            name="streams",
            field=models.ManyToManyField(
                blank=True, through="sbom.StreamBuild", to="sbom.stream"
            ),
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nvr", models.CharField(db_index=True, max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("version", models.CharField(max_length=128)),
                ("release", models.CharField(max_length=128)),
                ("arch", models.CharField(max_length=32)),
                (
                    "rpm_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("payload_hash", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="sbom.build",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "arch"],
                "unique_together": {("build", "nvr", "arch")},
            },
        ),
        migrations.CreateModel(
            name="ErrataInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=128)),
                ("product_version", models.CharField(max_length=128)),
                ("variants", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errata_infos",
                        to="sbom.stream",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "errata infos",
                "unique_together": {("stream", "product_name", "product_version")},
            },
        ),
        migrations.CreateModel(
            name="YumRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yum_repos",
                        to="sbom.stream",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "yum repos",
                "unique_together": {("stream", "url")},
            },
        ),
    ]
